# Generated by Django 6.0.4 on 2026-04-21 22:50

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('gender', models.CharField(db_index=True, max_length=10)),
                ('gender_probability', models.FloatField()),
                ('age', models.IntegerField()),
                ('age_group', models.CharField(max_length=10)),
                ('country_id', models.CharField(db_index=True, max_length=2)),
                ('country_name', models.CharField(max_length=50)),
                ('country_probability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
